### ISSUE TITLE
Addition of gate out when the arp or sequencer plays a new note

### ISSUE THREAD

**Issue by ghost** [icnagy/XIIO#4]
Is it possible to add a gate everytime the arp or sequence plays a new note? Currently it just plays a note when you press the touchplate but only then.

**Comment by icnagy** [comment]
It is certainly possible. How do you suppose to control the gate lengths?

**Comment by ghost** [comment]
Depends if its assignable, if not then default to 75% should be fine. If it is, whenever the arp/seq is on, if both ARP and Direction are touched then have it cycle 90%, 75%, 50%, and 25% gate length

**Comment by icnagy** [comment]
That would mean you'd loose two note plates while in arp/sequencer mode, certainly not a good idea. Let's go with fixed length for now. 
What module you're connecting it to? In most cases trigger out should be plenty enough.

**Comment by ghost** [comment]
That should be fine. I'm using a Mutable Peaks

**Comment by icnagy** [comment]
@GimbalSauce can you give that version a go?

**Comment by ghost** [comment]
Thanks for the work, i added some notes on the Pull of a small bug. Everything else is working as intended, thank you!

**Comment by icnagy** [comment]
Thank you! The gate length setting is now stored with the presets, and also the encoder direction is now properly saved.
